name: poc-next-postgres

services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres?schema=public'
      NODE_ENV: '${NODE_ENV:-production}'
      NEXT_TELEMETRY_DISABLED: '1'
      PORT: '3000'
    ports:
      - '3000:3000'

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: ./node_modules/.bin/prisma migrate deploy
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres?schema=public'
    depends_on:
      db:
        condition: service_healthy
